# Generated by Django 3.2.8 on 2021-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('2', 'Мужской'), ('1', 'Женский'), ('0', 'Иное')], default='0', max_length=1, verbose_name='пол'),
        ),
    ]
